{"name": "Проверка логина с неверным логином и паролем", "status": "passed", "start": 1706479170264, "stop": 1706479170509, "uuid": "7b95fe8a-2b03-45fb-a967-14260bef4b3c", "historyId": "deaa24b058a2227c3231554132b207fa", "testCaseId": "deaa24b058a2227c3231554132b207fa", "fullName": "tests.test_login.TestLogInUser#test_login_with_incorrect_log_and_pass_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogInUser"}, {"name": "host", "value": "DESKTOP-29U91I9"}, {"name": "thread", "value": "24328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}